### ISSUE TITLE
Item in wishlist deleted by store owner

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-wishlist#10]
**Fatal error:**

1. Save an item as wishlist
2. Delete the product from Dashboard

![image](https://user-images.githubusercontent.com/21140404/100517088-6432fb80-31b0-11eb-9a11-266236b68d9c.png)

3. Come back to wishlist page & try removing that product from wishlist page.

![image](https://user-images.githubusercontent.com/21140404/100517122-a52b1000-31b0-11eb-8e5e-8422e00dd508.png)

We get Fatal error if we try to delete product in wishlist which was initially deleted by the store owner.

**Comment by sonill** [comment]
its fixed.
