### ISSUE TITLE
Need to update Add to Cart button design in wishlist sidebar and wishlist table

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-wishlist#156]
In the new version, shortcode is used for displaying `Add to Cart` button. So CSS update for the button is required.

- [x] CSS update for the `Add to Cart` button is required in wishlist sidebar and wishlist table.

**Comment by h1dd3nsn1p3r** [comment]
Added style https://github.com/addonify/addonify-wishlist/commit/86fbaa6fc891b53a451b7d322a47c07111cbe6c0
