### ISSUE TITLE
DB upgrade success notice "Thanks!" button doesn't work.

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-wishlist#232]
👉 Describe the Bug:

DB upgrade success notice "Thanks!" button doesn't work.

👉 Expected Behaviour:

Once the "Thanks!" button is clicked, the success notice should hide immediately.

👉 Screenshots:

![image](https://user-images.githubusercontent.com/21140404/228470625-08d8bc47-7595-4a24-b8ba-062104e60218.png)

**Comment by diwakar2000** [comment]
fixed in commit #230
