### ISSUE TITLE
Placement of settings and options

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-wishlist#269]
- [x] 1. Create a section, `Style Options`. Place it after the section, `General Options`, of `General Settings` tab. The section contains two options, `Enable Styles from Plugin`, and `Custom CSS`. The option, `Enable Styles from Plugin`, is missing in the new setting. So add it.
- [x] 2. Move the section, `Save for Later`, to `Wishlist Button`. Place the section before `Button Labels` section. Rename the option label, `Button Label` to `Add to Wishlist Button Label`.

**Comment by diwakar2000** [comment]
fixed in commit #271

**Comment by Asok17** [comment]
- ~~[ ] Move `Style Options` section below `Product Removal Undo Notice` section inside `General Settings`.~~

**Comment by Asok17** [comment]
Placement of settings and options done in the commit #271.
