### ISSUE TITLE
Issue with database table creation

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-wishlist#279]
- [x] When WooCommerce is not activated, and Addonify Wishlist plugin is activated for the first time, addonify database table is not created.

**Comment by Asok17** [comment]
This error has occurred for MySQL version 5.7.

Recorded error in debug.log file is:

`WordPress database error Unknown error 1146 for query SHOW FULL COLUMNS FROM `wp_addonify_wishlist_table` made by activate_plugin, do_action('activate_addonify-wishlist/addonify-wishlist.php'), WP_Hook->do_action, WP_Hook->apply_filters, activate_addonify_wishlist, Addonify_Wishlist_Activator::activate, Addonify\Wishlist::insert_row`

Table creation is fine in MySQL version 8.

@diwakar2000

**Comment by diwakar2000** [comment]
issue addressed in #287

**Comment by Asok17** [comment]
Fixed in the commit #287
