### ISSUE TITLE
Needed updates in CSS of front-end elements

### ISSUE THREAD

**Issue by Asok17** [addonify/addonify-wishlist#289]
## 1. Wishlist Button

- ~~[ ] Do not apply CSS for background, background color and color. Doing so, the button will get it's CSS from theme.~~

## 2. Product Removal and Undo Notice

- [x] Font size for the notice is small. Let the font size be normal. It would be great if the Undo link displayed at the right most side of the notice.

## 3. Wishlist Page

- [x] It seems bottom margin is applied for the element, **_#addonify-wishlist-page-container_**. Use `margin-bottom` instead of `margin`. No need to specify left margin and top margin.

**Comment by h1dd3nsn1p3r** [comment]
1. Wishlist button - No changes done.

**Comment by Asok17** [comment]
Done in commint #289 #291
