### ISSUE TITLE
Move empty Wishlist text inside `"addonify-wishlist-empty"` div on the Wishlist page.

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-wishlist#314]
👉 Describe the Bug:

Move empty wishlist text inside `"addonify-wishlist-empty"` div on the wishlist page.

👉 How can we reproduce this Bug?

1. Add products to the wishlist.
2. Go to the wishlist page & remove all items in the wishlist.
3. Inspect the empty message.

👉 Screenshots:

![image](https://user-images.githubusercontent.com/21140404/234565384-9bebcf31-d05a-4797-9753-1bde80d1fc1a.png)

**Comment by Asok17** [comment]
Completed. #322
