### ISSUE TITLE
Change the Wishlist's page table add to cart button display to inline.

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [addonify/addonify-wishlist#315]
👉 Describe the Bug:

Change the wishlist's page table add to cart button display to inline.

👉 Screenshots:

![image](https://user-images.githubusercontent.com/21140404/234566204-f17bb2e0-3d87-46fe-8cbe-88d3238d9bf3.png)

**Comment by Asok17** [comment]
Completed #317
